#define I_INDEX_INVALIDATE		0x00

#define D_INDEX_WRITEBACK_INVALIDATE   0x01
#define D_INDEX_LOAD_TAG	0x05
#define D_INDEX_STORE_TAG	0x09

#define S_INDEX_STORE_TAG	0x0b
#define S_INDEX_LOAD_TAG	0x07
