# Auto-generated by BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/home/guobamantou/Desktop/edk2
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/home/guobamantou/Desktop/edk2/BaseTools/
fi
if [ -e /home/guobamantou/Desktop/edk2/BaseTools//BinWrappers/Linux-i686 ]
then
  if [ ${PATH//home/guobamantou/Desktop/edk2/BaseTools//BinWrappers/Linux-i686/} == $PATH ]
  then
    export PATH=/home/guobamantou/Desktop/edk2/BaseTools//BinWrappers/Linux-i686:$PATH
  fi
fi
